export enum PLAY_STATES {
  PLAYING = "PLAYING",
  PAUSED = "PAUSED",
  STOPPED = "STOPPED",
  LOADING = "LOADING",
}

export enum TRACK_LIST_ORIGIN_TYPE {
  PLAYLIST = "PLAYLIST",
  UPLOADED_TRACK = "UPLOADED_TRACK",
}

export const FORM_RATING_NULL_VALUE = -1;
