FROM node:14-alpine

ARG BODZIFY_API_UMG_USERNAME
ARG BODZIFY_API_UMG_USER_PASSWORD

ENV BODZIFY_API_UMG_USERNAME=${BODZIFY_API_UMG_USERNAME}
ENV BODZIFY_API_UMG_USER_PASSWORD=${BODZIFY_API_UMG_USER_PASSWORD}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
