export const PLAY_STATES = {
  PLAYING: "PLAYING",
  PAUSED: "PAUSED",
  STOPPED: "STOPPED",
  LOADING: "LOADING",
};

export const TRACK_LIST_ORIGIN_TYPE = {
  PLAYLIST: "PLAYLIST",
  LIB_TRACK: "LIB_TRACK",
};

export const PAGE_TYPES = {
  UPLOADED_TRACKS: "UPLOADED_TRACKS",
  GENRE_PLAYLISTS: "GENRE_PLAYLISTS",
  SPOTIFY_LIB_TRACKS: "SPOTIFY_LIB_TRACKS",
};

export const DUE_TO_PREVIOUS_ERROR_MESSAGE = "Error occurred during previous operation:";

export const FORM_RATING_NULL_VALUE = -1;
