export const PLAY_STATES = {
  PLAYING: "PLAYING",
  PAUSED: "PAUSED",
  STOPPED: "STOPPED",
  LOADING: "LOADING",
};

export const TRACK_LIST_ORIGIN_TYPE = {
  PLAYLIST: "PLAYLIST",
  UPLOADED_TRACK: "UPLOADED_TRACK",
};

export const PAGE_TYPES = {
  UPLOADED_LIBRARY: "UPLOADED_LIBRARY",
  GENRE_PLAYLISTS: "GENRE_PLAYLISTS",
  SPOTIFY_LIBRARY: "SPOTIFY_LIBRARY",
  ACCOUNT: "ACCOUNT",
};

export const DUE_TO_PREVIOUS_ERROR_MESSAGE = "Error occurred during previous operation:";

export const FORM_RATING_NULL_VALUE = -1;
